# Generated by Django 4.1.4 on 2022-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reqid', models.CharField(default='1', max_length=3)),
                ('fromLocation', models.CharField(max_length=255)),
                ('toLocation', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField()),
                ('assetQuantity', models.PositiveIntegerField()),
                ('assetType', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('TRAVEL_BAG', 'TRAVEL_BAG'), ('PACKAGE', 'PACKAGE')], max_length=50)),
                ('assetSensitivity', models.CharField(choices=[('HIGHLY_SENSITIVE', 'HIGHLY_SENSITIVE'), ('SENSITIVE', 'SENSITIVE'), ('NORMAL', 'NORMAL')], max_length=50)),
                ('whomToDeliver', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fromLocation', models.CharField(max_length=255)),
                ('toLocation', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField()),
                ('assetQuantity', models.PositiveIntegerField()),
                ('isApplied', models.BooleanField(default=False)),
                ('travelMedium', models.CharField(choices=[('Bus', 'BUS'), ('Car', 'CAR'), ('Train', 'TRAIN')], max_length=50)),
            ],
        ),
    ]
